# Generated by Django 2.2.3 on 2019-07-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=True)),
                ('question_2', models.CharField(choices=[('item_key1', '새벽'), ('item_key2', '아침'), ('item_key3', '낮'), ('item_key4', '저녁'), ('item_key5', '밤')], max_length=1)),
                ('question_3', models.CharField(choices=[('item_key1', '한국어'), ('item_key2', '영어'), ('item_key3', '일어'), ('item_key4', '중국어'), ('item_key5', '스페인어'), ('item_key6', '파이썬'), ('item_key7', '아랍어'), ('item_key8', 'C언어'), ('item_key9', '사랑의 언어'), ('item_key10', '제스쳐')], max_length=10)),
                ('question_4', models.TextField()),
                ('question_5', models.TextField()),
            ],
        ),
    ]
