# Generated by Django 2.2.3 on 2019-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='question_2',
            field=models.CharField(choices=[('1', '새벽'), ('2', '아침'), ('3', '낮'), ('4', '저녁'), ('5', '밤')], max_length=1),
        ),
        migrations.AlterField(
            model_name='info',
            name='question_3',
            field=models.CharField(choices=[('1', '한국어'), ('2', '영어'), ('3', '일어'), ('4', '중국어'), ('5', '스페인어'), ('6', '파이썬'), ('7', '아랍어'), ('8', 'C언어'), ('9', '사랑의 언어'), ('10', '제스쳐')], max_length=10),
        ),
    ]
